general:
    name: 'graph_dit'
    wandb: 'disabled' 
    gpus: 1
    resume: null
    test_only: null
    sample_every_val: 2500
    samples_to_generate: 512      
    samples_to_save: 3
    chains_to_save: 1
    log_every_steps: 50
    number_chain_steps: 8
    final_model_samples_to_generate: 10000
    final_model_samples_to_save: 20
    final_model_chains_to_save: 1
    enable_progress_bar: true
    save_model: True
model:
    type: 'discrete'
    transition: 'marginal'
    model: 'graph_dit'
    diffusion_steps: 500
    diffusion_noise_schedule: 'cosine'
    guide_scale: 2
    hidden_size: 1152
    depth: 6
    num_heads: 16
    mlp_ratio: 4
    drop_condition: 0.01
    lambda_train: [1, 10]  # node and edge training weight
    ensure_connected: True

    # Enhanced model features
    use_enhanced: true
    use_edge_aware_attention: true
    use_cross_attention: true
    use_adaptive_weighting: true

    # Fast sampling settings
    use_fast_sampling: true
    fast_steps: 50  # Much faster than 500 steps
    ddim_eta: 0.0  # Deterministic sampling

    # Chemical constraints
    use_constraints: true
    valence_weight: 10.0
    connectivity_weight: 5.0
    symmetry_weight: 1.0
    constraint_initial: 0.1
    constraint_final: 1.0
    constraint_warmup: 1000
    constraint_guidance: 1.0
train:
    n_epochs: 10000
    batch_size: 100
    lr: 0.0002
    clip_grad: null
    num_workers: 0
    weight_decay: 0
    seed: 0
    val_check_interval: null
    check_val_every_n_epoch: 1
dataset:
    datadir: 'data/'
    task_name: null
    guidance_target: null
    pin_memory: False
